### ISSUE TITLE
Route not found

### ISSUE THREAD

**Issue by silasrm** [dextervip/DatabaseSwiftMailerBundle#1]
Hi,

I'm following the all steps to install and configure, including "Overriding default templates", but when I go accessing that url myapp.dev/email-spool return this:

No route found for "GET /email-spool"

How to fix this?

**Comment by dextervip** [comment]
Hi,

I guess It's something wrong with your routes configuration. Did you add this route config in your routing.yml?

``` yml
citrax_database_swift_mailer:
    resource: "@CitraxDatabaseSwiftMailerBundle/Controller/"
    type:     annotation
    prefix:   /
```

Or try accessing: http://yourapp/email-spool/1
